import './reset.css'
import './globals.css'

export const runtime = 'edge'
export const metadata = {
  title: 'Strava stats',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <div>{children}</div>
          <div className="footer">
            &copy; spathon | <a href="https://github.com/spathon/StravaStats">Code</a>
          </div>
        </div>
      </body>
    </html>
  )
}
